### ISSUE TITLE
E492: Not an editor command: LoadComments

### ISSUE THREAD

**Issue by fernandoalex** [oxytocin/DocComments#2]
Unfortunately not working for me, installed with `Plug` but as soon as I open nvim I get the following error:

```
Error detected while processing VimEnter Autocommands for "*":
E492: Not an editor command: LoadComments
```
No commands from the plugin are loaded.

Using nvim head
```
$ nvim --version
NVIM v0.7.0-dev+956-g6cb670cb2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ...

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-6cb670c/share/nvim"

Run :checkhealth for more info
```

Please let me know any other information that may be useful.

Love the idea of the plugin btw

**Comment by oxytocin** [comment]
Thank you for the bug report. Could you try running `UpdateRemotePlugins` and restarting Neovim?

**Comment by fernandoalex** [comment]
Thanks for the response @oxytocin , I added `pip3 install neovim` and ran `UpdateRemotePlugind` and this problem went away, but as soon as I tried to create a comment with `MakeComment` I got another error.

```
error caught in async handler '/Users/USER/.local/share/nvim/plugged/DocComments/rplugin/python3/DocComments.py:command:MakeComment [[39, 39]]'
Traceback (most recent call last):
  File "/Users/USER/.local/share/nvim/plugged/DocComments/rplugin/python3/DocComments.py", line 91, in make_comment
    self.nvim.api.buf_set_extmark(0, self.ns, start_row, start_col, options)
  File "/usr/local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: end_row value outside range
```

Tested with strings:

`test`
`test comment`

Since it is not related to the initial problem, shall I make another issue?

Again thanks for the help 🙇
